Fix logicalFilePath not being serialized - Fixes #1234
liquibase/liquibase pull request #1471
Opened 2020-10-12 14:35 UTC by tms-91

---
name: Pull Request
about: Create a report to help us improve
title: ''
labels: Status:Discovery
assignees: ''

---

## Environment

**Liquibase Version**: 3.10.3

**Liquibase Integration & Version**: maven

**Liquibase Extension(s) & Version**: mssql-jdbc-8.4.1.jre8.jar

**Database Vendor & Version**: MSSQL

**Operating System Type & Version**: Windows 10

## Pull Request Type

closes #1234 
- [x] Bug fix (non-breaking change which fixes an issue.)
- [ ] Enhancement/New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description
See #1234 

## Steps To Reproduce
See #1234 

## Actual Behavior
The logicalFilePath attribute of a ChangeSet is not serialized.

## Expected/Desired Behavior
The logicalFilePath attribute of a ChangeSet is serialized.

## Additional Context
<changeSet author="tms"  dbms="mssql" id="1" logicalFilePath="path/to/file.json"/>

## Fast Track PR Acceptance Checklist:

- [x] Build is successful and all new and existing tests pass
- [x] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
- [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
- [ ] Documentation Updated

## Need Help?
Come chat with us on our [discord channel](https://discord.com/channels/700506481111597066/700506481572839505)

2021-06-08 19:26 UTC, nvoxland requested changes
The issue with this implementation is that it makes any usage of a filePath stored in the changeSet bet serialized out as logicalFilePath.

For example, I if I just run `liquibase generate-changelog` then I get changeSets like 

```
    <changeSet author="nathan (generated)" id="1623168864769-2" logicalFilePath="out.xml">
```
which should not include logicalFilePath.

To handle that better, the PR probably has to be updated to be able to tell the difference between a logicalFilePath that was explicitly set as a logicalFilePath and ones that are just defaulting to the changelog's filePath (physical of logical).

I did not yet test that the extra serialization impacts the checksums of the changeSets or not. The serialization logic fits into there, so we need to make sure it doesn't change (and break) checksums for changesets.

2021-06-08 19:52 UTC, nvoxland commented
I pushed fixes for the merge conflicts back up to your branch. Since that branch is just 3.10.x on your side, it is now quite different than liquibase's 3.10.x...

2021-06-08 20:01 UTC, nvoxland approved these changes
I ended up just making the changes the PR needed and pushing it to your fork while I was in there and thinking about it.

Take a look and LMK what you think.

I also checked the checksum logic, and none of the attributes on changeSet are used in the checksum logic. Only the checksums of the inner changes. So that is no worry.

2021-06-09 22:33 UTC, suryaaki2 approved these changes

2021-07-28 21:58 UTC, merged