fixed generating sequences for postgre versions prior to 10
liquibase/liquibase pull request #1843
Opened 2021-05-13 14:44 UTC by KushnirykOleh

## Environment

**Liquibase Version**:  4.4.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: PostgreSQL version < 10

**Operating System Type & Version**: Mac OS Catalina 10.15.7

## Pull Request Type

- [x] Bug fix (non-breaking change which fixes an issue.) closes #1429  https://datical.atlassian.net/browse/LB-704
- [ ] Enhancement/New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

PostreSQL doesn't support "AS datatype" structure in sequences prior to version 10. So SQL that Liquibase generates with "AS [datatype]" fails for those postgreSQL versions. fixed that.

## Steps To Reproduce
- run PostreSQL 9.5 on perm, in docker container or elsewhere
- take changelog file from test harness https://github.com/liquibase/liquibase-test-harness/blob/974f3adeac5225929fef9580bede0ed7c72b7733/src/main/resources/liquibase/harness/change/changelogs/postgresql/createSequence.xml or create your own with **createSequence** changeType
- run Liquibase update command for such file against PostreSQL 9.5 
- verify it fails with query "CREATE SEQUENCE  IF NOT EXISTS test_sequence AS int START WITH 1 INCREMENT BY 1 MINVALUE 1"

with [test harness](https://github.com/liquibase/liquibase-test-harness)
1) Make sure you have a docker container up and running first
2) Go to `src/test/resources/docker` and run `docker-compose up -d`. 
Wait until the databases start up.
3) run mvn test -DchangeObjects=createSequence,dropSequence
4) _createSequence_ and _dropSequence_ tests fails for postre 9 & 9.5

## Actual Behavior
 Liquibase generates "CREATE SEQUENCE  IF NOT EXISTS test_sequence AS int START WITH 1 INCREMENT BY 1 MINVALUE 1" for all PostgreSQL versions and this query fails for version prior to 10

## Expected/Desired Behavior
for PostgreSQL 10 and later nothing should change, query should remains the same, for PostgreSQL prior to version 10 it should be like this "CREATE SEQUENCE  IF NOT EXISTS test_sequence START WITH 1 INCREMENT BY 1 MINVALUE 1"

## Fast Track PR Acceptance Checklist:

- [x] Build is successful and all new and existing tests pass
- [x] Added [Unit Test(s)]
- [ ] Added [Integration Test(s)]
- [x] Added [Test Harness Test(s)](https://github.com/liquibase/liquibase-test-harness/pulls) - didn't add, they already exist there. test harness helped to find this issue https://github.com/liquibase/liquibase-test-harness/blob/974f3adeac5225929fef9580bede0ed7c72b7733/src/main/resources/liquibase/harness/change/changelogs/postgresql/createSequence.xml checked with local liquibase-core snapshot - with this fix it works for PostreSQL 9, 9.5, 10, 11, 12, 13
[ ] Documentation Updated

2021-05-14 04:28 UTC, molivasdat commented
Thanks @KushnirykOleh for fixing this issue.

2021-05-21 16:34 UTC, nvoxland requested changes

2021-05-24 11:42 UTC, KushnirykOleh commented on liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java
> +        try {
What's expected behaviour when can't determine version? Add validation error or not?

2021-05-26 14:23 UTC, nvoxland approved these changes

2021-05-26 20:56 UTC, suryaaki2 approved these changes

2021-06-24 20:50 UTC, merged