DAT-6808 strip password from jdbc url
liquibase/liquibase pull request #1844
Opened 2021-05-13 20:16 UTC by suryaaki2

This ticket strips password from oracle thin jdbc url format

## Environment

**Liquibase Version**:

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

## Pull Request Type

- [ ] Bug fix (non-breaking change which fixes an issue.)
- [ ] Enhancement/New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

A clear and concise description of the issue being addressed.  Additional guidance [here](https://liquibase.jira.com/wiki/spaces/LB/pages/1274904896/How+to+Contribute+Code+to+Liquibase+Core).
- Describe the actual problematic behavior.
- Ensure private information is redacted.

## Steps To Reproduce

List the steps to reproduce the behavior.
- Please be precise and ensure private information is redacted
- Include things like
  - Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  - Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

## Actual Behavior
A clear and concise description of what happens in the software **before** this pull request.
- Include console output if relevant
- Include log files if available.

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** this pull request.

## Screenshots (if appropriate)
If applicable, add screenshots to help explain your problem.

## Additional Context
Add any other context about the problem here.

## Fast Track PR Acceptance Checklist:

- [ ] Build is successful and all new and existing tests pass
- [ ] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
- [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
- [ ] Added [Test Harness Test(s)](https://github.com/liquibase/liquibase-test-harness/pulls)
- [ ] Documentation Updated

## Need Help?
Come chat with us on our [discord channel](https://discord.com/channels/700506481111597066/700506481572839505)

2021-05-14 04:28 UTC, molivasdat commented
Thanks @suryaaki2 for fixing this.

2021-05-14 15:29 UTC, wwillard7800 commented on liquibase-core/src/main/java/liquibase/database/jvm/JdbcConnection.java
> +   public static class Pair {
Since Pair exists as an internal class in the Java world, you might rename this to something like **PatternPair** to distinguish it.

2021-05-17 16:33 UTC, nvoxland requested changes

2021-05-17 16:33 UTC, nvoxland commented on liquibase-core/src/main/java/liquibase/database/jvm/JdbcConnection.java
> +    public static String stripPasswordPropFromJdbcUrl(String jdbcUrl) {
You can't change public APIs, that breaks backwards compatibility

2021-05-17 16:33 UTC, nvoxland commented on liquibase-core/src/main/java/liquibase/database/jvm/JdbcConnection.java
> +   public static class PatternPair {
This should be private so it's not part of our API

2021-05-17 18:18 UTC, nvoxland approved these changes

2021-05-25 20:05 UTC, merged