Fix Additional unfixed issues with relativeToChangelogfile + logicalFilePath
liquibase/liquibase pull request #2758
Opened 2022-04-14 15:14 UTC by erik-meuwese-topicus

## Environment

**Liquibase Version**: 4.9.1

**Liquibase Integration & Version**: Spring-Boot 2.4.3

**Database Vendor & Version**: Postgresql 12.10

## Pull Request Type

- [ ] Bug fix (non-breaking change which fixes an issue.)
- [ ] Enhancement/New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

To make changelogs from liquibase 3.x.x with sqlFile path referring to an sql file in the same dir with relativeToChangelogFile="true" work with 4.x.x  https://github.com/liquibase/liquibase/issues/2281

## Steps To Reproduce

file:/...../target/classes/liquibase/init/test.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
                   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd">
    <changeSet>
        <sqlFile path="test.sql" relativeToChangelogFile="true" splitStatements="false"/>
    </changeSet>
</databaseChangeLog>
```
file:/...../target/classes/liquibase/init/test.sql

Liquibase 4.9.1 fails to find test.sql relative to test.xml which contains the changelog

## Actual Behavior
```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LiquibaseException: liquibase.exception.UnexpectedLiquibaseException: java.io.IOException: The file test.sql was not found in
    - file:/...../target/classes/
    - file:/...../target/classes/
Specifying files by absolute path was removed in Liquibase 4.0. Please use a relative path or add '/' to the classpath parameter.
```

## Expected/Desired Behavior
```
2022-04-14 16:06:45.705  INFO 36588 --- [  restartedMain] liquibase.database                       : Set default schema name to public
2022-04-14 16:06:45.910  INFO 36588 --- [  restartedMain] liquibase.lockservice                    : Successfully acquired change log lock
2022-04-14 16:06:46.688  INFO 36588 --- [  restartedMain] liquibase.changelog                      : Reading from public.databasechangelog
Running Changeset: liquibase/init/test.xml::test-003::tester
2022-04-14 16:06:46.930  INFO 36588 --- [  restartedMain] liquibase.changelog                      : SQL in file test.sql executed
2022-04-14 16:06:46.938  INFO 36588 --- [  restartedMain] liquibase.changelog                      : ChangeSet liquibase/init/test.xml::test-003::tester ran successfully in 80ms
2022-04-14 16:06:46.966  INFO 36588 --- [  restartedMain] liquibase.lockservice                    : Successfully released change log lock
```

## Additional Context
See discussion in: https://github.com/liquibase/liquibase/issues/2281

## Fast Track PR Acceptance Checklist:

- [ ] Build is successful and all new and existing tests pass  (SimpleSqlGrammarTest.test:20 failed on tag 4.9.1 before and after proposed change)
- [ ] Added [Unit Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1274937609/How+to+Write+Liquibase+Core+Unit+Tests)
- [ ] Added [Integration Test(s)](https://liquibase.jira.com/wiki/spaces/LB/pages/1276608569/How+to+Write+Liquibase+Core+Integration+Tests)
- [ ] Added [Test Harness Test(s)](https://github.com/liquibase/liquibase-test-harness/pulls)
- [ ] Documentation Updated

2022-05-17 22:05 UTC, nvoxland commented
@erik-meuwese-topicus thanks for tracking down and describing the `exists()` problem in https://github.com/liquibase/liquibase/issues/2281#issuecomment-1021036440 and making the PR for it.

I am not able to reproduce the problem to see your change fix it due to not getting spring set up in whatever configuration exposes it, but I understand how this can solve it.

I did push a change where I extracted the DefaultResourceLoader creation to the constructor and made a new `getResource(String)` method to wrap the logic you added to make it more extendable by people with other odd resource loader configurations. I also didn't want to completely abandon the regular resourceLoader in case it's able to find things not in the classpath. **Can you check that my changes didn't break your fix, @erik-meuwese-topicus ?**

I also updated the description to have it a bit more focused on the exists() problem vs. a more generic "fixes spring boot". Let me know if there is anything I got wrong in that change

2022-05-17 22:08 UTC, nvoxland approved these changes
Code review and test results:

Things to be aware of
- I couldn't reproduce the problem to see the fix work, but I was able to tell the change didn't break the setup I had
- Fix improves the handling within certain spring boot setups without impacting others by falling back to the old logic if the new lookup doesn't find a resource

Things to worry about
- No tests added, but I need to spend more time that we have right now to figure out the right way to integrate spring testing into our suite. Unit tests didn't seem like they'd add enough value to come up with.

2022-05-18 12:27 UTC, XDelphiGrl approved these changes
* Code change introduces an appropriate redundancy check for ensuring Liquibase loads the expected classpath.
* Change is limited to Spring Boot.

**Please Note!**  @nvoxland (Liquibase Founder) and several other Liquibase Engineers reviewed the code change and deem it low risk. However, there are no automated functional tests in place for Spring Boot. Be advised there is a larger possibility of unexpected side-effect due to the change than for similar changes with robust testing in place.

2022-05-18 12:30 UTC, XDelphiGrl requested changes
I submitted a PR approval but just noticed that the build did not complete. Requesting that the build run and pass all developer-level tests prior to merging this fix.

2022-05-18 23:31 UTC, suryaaki2 approved these changes

2022-05-19 02:46 UTC, merged

2022-11-08 14:18 UTC, erik-meuwese-topicus commented
[nvoxland] this fixed our issue, thanks