add liquibase flow and flow.validate goals to maven plugin (DAT-10576)
liquibase/liquibase pull request #3015
Opened 2022-06-28 14:12 UTC by StevenMassaro

## Impact

- [X] Bug fix (non-breaking change which fixes expected existing functionality)
- [X] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Add a `flow` and `flow.validate` goal to the maven plugin. Also, add class check before casting in `Main.java`.

## Things to be aware of

Not all Liquibase commands will work out of the box when executed through flow and the maven integration.

## Things to worry about

See above.

## Additional Context

2022-06-28 15:04 UTC, nvoxland approved these changes

2022-06-28 19:36 UTC, abrackx approved these changes

2022-07-01 16:44 UTC, abrackx requested changes
merge freeze 🥶

2022-07-12 14:13 UTC, suryaaki2 approved these changes

2022-07-13 16:20 UTC, merged