DAT-11294 The onSqlOutput attribute does not work for preconditions in formatted SQL changelogs.
liquibase/liquibase pull request #3436
Opened 2022-11-03 11:32 UTC by dyadyushko

## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

A clear and concise description of the change being made.  

- Introduce what was/will be done in the title
  - Titles show in release notes and search results, so make them useful
  - Use verbs at the beginning of the title, such as "fix", "implement", "improve", "update", and "add" 
  - Be specific about what was fixed or changed
  - Good Example: `Fix the --should-snapshot-data CLI parameter to be preserved when the --data-output-directory property is not specified in the command.`
  - Bad Example: `Fixed --should-snapshot-data`  
- If there is an existing issue this addresses, include "Fixes #XXXX" to auto-link the issue to this PR
- If there is NOT an existing issue, consider creating one.
  - In general, issues describe wanted change from an end-user perspective and PRs describe the technical change.
  - If this change is very small and not worth splitting off an issue, include `Steps To Reproduce`, `Expected Behavior`, and `Actual Behavior` sections in this PR as you would have in the issue.
- Describe what users need and how the fix will affect them
- Describe how the code change addresses the problem
- Ensure private information is redacted.

## Things to be aware of

- Describe the technical choices you made
- Describe impacts on the codebase

## Things to worry about

- List any questions or concerns you have with the change
- List unknowns you have 

## Additional Context

Add any other context about the problem here.

2022-11-03 13:39 UTC, suryaaki2 requested changes

2022-11-03 13:39 UTC, suryaaki2 commented on liquibase-core/src/main/java/liquibase/parser/core/formattedsql/FormattedSqlChangeLogParser.java
> +                                if (onSqlOutputMatcher.matches()) {
@dyadyushko Can you handle the condition that if changelog contains both onUpdateSql and onSqloutput in which case, we should throw an error, "Please modify the changelog to have preconditions set with either "onUpdateSql" or "onSqlOutput"?

2022-11-04 17:41 UTC, nvoxland approved these changes

2022-11-04 18:03 UTC, suryaaki2 approved these changes

2022-11-04 18:14 UTC, filipelautert approved these changes

2022-11-08 13:43 UTC, merged