add update summary object to MDC (DAT-13153)
liquibase/liquibase pull request #3800
Opened 2023-02-09 18:18 UTC by StevenMassaro

## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [X] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

## Things to be aware of

## Things to worry about

## Additional Context

2023-02-09 19:07 UTC, suryaaki2 requested changes

2023-02-09 19:07 UTC, suryaaki2 commented on liquibase-core/src/main/java/liquibase/logging/mdc/customobjects/UpdateSummary.java
> +
Can we have a java doc comment on what this updateSummary class is all about?

2023-02-10 03:40 UTC, filipelautert approved these changes

2023-03-08 12:30 UTC, filipelautert approved these changes

2023-03-23 13:04 UTC, suryaaki2 approved these changes

2023-03-31 14:44 UTC, merged