Enhance empty string check.
liquibase/liquibase pull request #3804
Opened 2023-02-10 06:18 UTC by Jeevananthammoorthy

## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

## Things to be aware of

## Things to worry about

## Additional Context

2023-02-10 14:35 UTC, MalloD12 commented
Hi @Jeevananthammoorthy thank you for creating this PR for us. The updated class is not the only place where we have this type of occurrence of this type of validation. Looking quickly through the code I have seen there several other places where we would need to update this as well. Would you mind looking for these classes and performing the same change over there?

Thanks,
Daniel.

2023-02-10 15:11 UTC, Jeevananthammoorthy commented
> Hi @Jeevananthammoorthy thank you for creating this PR for us. The updated class is not the only place where we have this type of occurrence of this type of validation. Looking quickly through the code I have seen there several other places where we would need to update this as well. Would you mind looking for these classes and performing the same change over there?
> 
> Thanks, Daniel.

Got it, will push the updated patch

2023-02-10 15:47 UTC, Jeevananthammoorthy commented
@MalloD12  QQ: Is it okay to create new PR with the requested review comments? Am using githubDesktop, and I couldn't find away to update this commit.
Lmk if any issue, in raising new PR. the changes are ready in my local.

2023-02-14 01:14 UTC, Jeevananthammoorthy commented
@MalloD12  Sure, will push update patch in sometime including null check before isEmpty().

Thanks,
Jeevanantham

2023-02-14 01:27 UTC, MalloD12 commented
> @MalloD12 Sure, will push update patch in sometime including null check before isEmpty().
> 
> Thanks, Jeevanantham

I think it would depend on a case basis, maybe not all the cases need this null check. 

Thanks,
Daniel.

2023-02-14 06:36 UTC, Jeevananthammoorthy commented
@MalloD12  Updated the patch, kindly review.

Thanks,
Jeevanantham

2023-02-21 18:04 UTC, MalloD12 commented
> @MalloD12 Updated the patch, kindly review.
> 
> Thanks, Jeevanantham

I have some unit tests failing, and I still need to confirm whether there is any relationship with the changes implemented in this PR or not. I might need to spend a bit more time on this. Also, I noticed today this PR has been created directly from your master branch, we should be creating a dedicated branch with a representative name of the changes we are trying to implement here. I'll keep you posted once I can determine the cause of these failing unit tests.

Thanks,
Daniel.

2023-04-25 19:43 UTC, MalloD12 commented
This PR is a minor extension from https://github.com/liquibase/liquibase/pull/3590 where we discussed with the team adding String `isEmpty()` check, instead of doing something like `"".equals(<stringToCompareAgainst>)`. After we added some changes here the build of this PR started having some issues which might require a little bit more time to investigate the root cause of it, whether it's directly related to changes made here or if it's something else.

Move it back to "Foundation" queue for further prioritization, or we can also close it if we consider it is not worth expending too much time on it for the extra value it will provide us.

cc: @mariochampion

2023-05-09 18:46 UTC, filipelautert approved these changes

2023-05-09 18:46 UTC, filipelautert commented on liquibase-standard/src/main/java/liquibase/parser/core/xml/XMLChangeLogSAXHandler.java
> +            if (!StringUtil.isEmpty(trimmedString)) {
Hello @Jeevananthammoorthy ! Can't we use the new "StringUtil.isBlank" here and in some other places instead of trimToEmpty then isEmpty?

2023-05-09 18:49 UTC, filipelautert requested changes
Please see my comments in the code.

2023-06-22 15:23 UTC, closed without merging

2023-08-25 14:27 UTC, filipelautert commented
@kevin-atx - it wasn't merged. The contributor removed their repository and with that the PR was closed.

2023-08-28 21:20 UTC, kevin-atx commented
that makes sense - thanks!