Safely call snakeyaml methods that have been changed in last versions.
liquibase/liquibase pull request #3904
Opened 2023-03-06 11:56 UTC by filipelautert

## Impact

- [X] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Safely call snakeyaml method that had signature changes in 1.3? series.

## Things to be aware of

Changes to show the warning message only once.

## Things to worry about

None

## Additional Context

Closes #3878

2023-03-06 14:06 UTC, StevenMassaro requested changes
I am tempted to say (partially joking) that we should call every SnakeYaml method using these safe methods, since they make so many breaking changes.

2023-03-06 16:22 UTC, StevenMassaro approved these changes

2023-03-06 16:23 UTC, suryaaki2 approved these changes

2023-03-06 22:05 UTC, XDelphiGrl approved these changes
In 4.19.1, Liquibase deprecated usage of 1.x SnakeYaml classes in preparation for an upgrade to SnakeYaml 2.0, which removes those classes entirely. This introduced a bug that if an older SnakeYaml version loaded into the Liquibase classpath, a NoSuchMethodError is thrown when Liquibase attempts to call a method that does not exist in the 1.x version of SnakeYaml. This issue was identified and addressed in the 4.19.1 PR for `setCodePointLimit` but the `setProcessComments` call was missed. This PR addresses `setProcessComments` and consolidates WARNINGs into one message.

[Original PR Discussion about setCodePointLimit](https://github.com/liquibase/liquibase/pull/3632#discussion_r1107130558)

* Manual testing of this fix completed using CLI and SpringBoot.
* Functional and test harness executions passing.
* No additional testing required.

APPROVED

2023-03-07 01:13 UTC, merged

2023-03-07 13:17 UTC, XDelphiGrl commented
I reproduced the bug with both SpringBoot and the CLI using Liquibase 4.19.1. Manual tests for both interfaces validate behavior with SnakeYaml versions 1.29, 1.32 and 1.33. The Springboot project builds a SpringBoot v2.5.3 application using Maven 3.8.1. SpringBoot JPA 2.5.3 depends on SnakeYaml 1.28, which triggers the bug with 4.19.1.

**CLI Validations**

CLI testing is performed by swapping out the version of SnakeYaml in the liquibase/internal/lib directory. 

**CASE 1** Verify Liquibase does not return a WARNING or ERROR using the bundled snakeyaml.jar (which is v1.33). **PASS**
**CASE 2** Verify Liquibase returns a WARNING when liquibase/lib/internal contains snakeyaml-1.29.jar. **PASS**
**CASE 3** Verify Liquibase does not return a WARNING or ERROR when liquibase/lib/internal contains snakeyaml-1.32 (min version to be backwards compatible). **PASS**
**CASE 4** Verify Liquibase returns a WARNING when liquibase/lib contains snakeyaml-1.29.jar and there is no SnakeYaml in liquibase/internal/lib. **PASS**
**CASE 5** Verify Liquibase does not return a WARNING or ERROR when liquibase/lib contains snakeyaml-1.32. **PASS**


**SpringBoot Validations**
The first two test cases are executed during Package, which in my project is configured to run tests that deploy changesets.

**CASE 6** Verify mvn package throws a WARNING but continues to deploy changesets when snakyaml version is NOT pinned in the pom.xml. **PASS**
**CASE 7** Verify mvn package does not throw a WARNING or ERROR and continues to deploy changesets when snakeyaml version is pinned to 1.32 in the pom.xml. **PASS**

The next two test cases are executed by directly running the jar created during Package. On application startup, changesets are deployed. 

**CASE 8** Verify java -jar throws a WARNING but deploys changesets when snakyaml version is not pinned in the pom.xml. **PASS**
**CASE 9** Verify java -jar throws deploys changesets when snakyaml version is pinned to 1.32 in the pom.xml without a WARNING or ERROR. **PASS**

---
**Test Environment**
OSS: //3878-snakeyaml-nosuchmethod-issue/7810/384572
Commercial: master/2905/c9f417
Postgres 12.6
SpringBoot JPA (2.5.3)
Maven 3.8.1