Reworks liquibaseOperation MdcKey to liquibaseInternalOperation (DAT-13996]
liquibase/liquibase pull request #4065
Opened 2023-04-03 12:03 UTC by abrackx

## Impact

- [] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

## Things to be aware of

## Things to worry about

## Additional Context

2023-04-04 12:39 UTC, StevenMassaro requested changes

2023-04-04 12:39 UTC, StevenMassaro commented on liquibase-core/src/main/java/liquibase/Liquibase.java
I think there are constant fields with the command names in them somewhere, can you use those instead of hardcoding the string?

2023-04-04 12:39 UTC, StevenMassaro commented on liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
Can you replace usages of `internalCommand` with their `COMMAND_NAME` from the respective class, rather than hardcoding?

2023-04-04 14:22 UTC, abrackx commented on liquibase-core/src/main/java/liquibase/integration/commandline/Main.java
These are internal commands from pro, so I can't take that route

2023-04-04 14:43 UTC, StevenMassaro commented on liquibase-core/src/main/java/liquibase/Liquibase.java
You made the right call, don't add them.

2023-04-04 14:44 UTC, StevenMassaro approved these changes

2023-04-04 14:47 UTC, filipelautert approved these changes

2023-04-05 13:14 UTC, filipelautert approved these changes

2023-04-07 13:18 UTC, merged