Added changesetOperationStop time to exception handling also made all start/stop times be UTC DAT-13963
liquibase/liquibase pull request #4078
Opened 2023-04-04 13:52 UTC by wwillard7800

## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

## Things to be aware of

## Things to worry about

## Additional Context

2023-04-04 17:14 UTC, suryaaki2 requested changes

2023-04-04 17:14 UTC, suryaaki2 commented on liquibase-core/src/main/java/liquibase/changelog/ChangeSet.java
> +        String startTimeString = Instant.ofEpochMilli(startTime).toString();
Should we add a method getStartTime() instead of duplicating the code at 3 places?

2023-04-04 17:19 UTC, filipelautert approved these changes
Agree with @suryaaki2 comments.. or maybe remove the  "[start|stop]TimeString" and move the conversion straight to where it is used?

2023-04-04 18:24 UTC, filipelautert approved these changes

2023-04-06 17:07 UTC, suryaaki2 approved these changes

2023-04-06 17:07 UTC, merged