Dat 14642
liquibase/liquibase pull request #4193
Opened 2023-04-28 19:55 UTC by filipelautert

## Impact

- [X] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 
## Description

Fix handling of ChangeLogHistoryServiceFactory when dealing with checksum upgrades.

2023-04-28 20:00 UTC, wwillard7800 reviewed
Looks good

2023-04-28 20:01 UTC, suryaaki2 approved these changes

2023-05-01 21:03 UTC, nvoxland requested changes

2023-05-01 21:03 UTC, nvoxland commented on liquibase-standard/src/main/java/liquibase/Liquibase.java
> +            ChangeLogHistoryServiceFactory.getInstance().resetAll();
This feels like a fix at the wrong level. The "resetAll" is sort of a "this code knows something the history service doesn't" hack when code outside the historyservice messes with the underlying data. But if you had just called "upgradeChecksums" the history service should know about what's going on.

That makes it feel like the actual bug is a problem with caching or something in the history service. Or, from doing a bit of debugging with daniel, a problem with how we're managing the history service singleton. 

There are possibly other places in our code and for sure places in other peoples code where they are calling methods on the history service and expecting it to work correctly. If the problem is that we're not seeing it work correctly unless we start calling resetAll, we can't be expecting us or others to fix their code, we should fix the service.

2023-05-03 18:35 UTC, XDelphiGrl commented
Passing functional tests for Postgres are here: [https://github.com/liquibase/liquibase-pro-tests/actions/runs/4872052466](https://github.com/liquibase/liquibase-pro-tests/actions/runs/4872052466). The issue was that there is a test validation fix for the `calculate-checksum` tests that was not in liquibase-pro-tests master when the build triggered. This run used the test PR with the validation fix and this PR branch of Liquibase.

2023-05-05 19:36 UTC, merged