DAT-13450
liquibase/liquibase pull request #5157
Opened 2023-11-02 18:37 UTC by sayaliM0412

remove liquibase-extension-examples module and references

## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [x] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

## Things to be aware of

## Things to worry about

## Additional Context

2023-11-03 19:24 UTC, obovsunivskyii commented
@sayaliM0412 can you please resolve conflicts here?

2023-11-15 21:12 UTC, rberezen approved these changes

2023-11-16 12:54 UTC, filipelautert approved these changes

2023-11-16 12:57 UTC, filipelautert requested changes
Seems that after the last merges pom.xml file removal was ignored?

2023-11-16 20:03 UTC, merged