Fix #5271: ColumnExistsPrecondition throws error when table is missing
liquibase/liquibase pull request #5282
Opened 2023-11-24 14:01 UTC by Januson

- Handled DatabaseException thrown by PreparedStatement when the table is missing
- Added integration test

Fixes #5271

## Impact

- [x ] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

This PR fixes a bug introduced in 4.25.0 where ColumnExistsPrecondition fails with an error PreconditionErrorException when table that is supposed to contain the column is missing.

## Things to be aware of

## Things to worry about

## Additional Context

2023-11-24 14:47 UTC, tati-qalified commented
Testing this PR should include this use case: #5246 
We're assuming it's the same problem in two different scenarios

2023-11-24 15:12 UTC, Januson commented
@tati-qalified Their use-case should be covered by the integration test I added. It uses <not> and is not limited to only hsqldb so it verifies h2 as well.

2023-11-28 18:25 UTC, tati-qalified commented
Hi @Januson, currently this PR is working for the `columnExists` precondition, but failing when it's wrapped with the `not` tag. This happens with both HyperSQL and H2. 
We are currently creating a fix for it, but if you have any ideas feel free to include them.
Thanks!
Tatiana

2023-11-29 18:06 UTC, tati-qalified requested changes
Please add `.close()` to `ColumnExistsPrecondition.java#165`.

Other than that, it works with HyperSQL, H2 and PostgreSQL.

2023-11-30 15:19 UTC, Januson commented
@MalloD12 Ok. So should I close this PR and we'll use the one you opened?

No. I think the use of try-with-resources is the right call. When opening the PR I assumed there's a reason you are using that utility to close it in finally, so I tried to touch bare minimum needed for the fix. I think the CodeQL scan is reporting the issue @tati-qalified mentioned above. ResultSet was left unclosed.

2023-11-30 21:22 UTC, MalloD12 approved these changes
**Approved**.

## Review and testing results:
Thanks again @Januson for the fix and test you provided here. The code changes look good to me. From my side I only fixed some code smells and codeQL reported warnings, plus some manual testing we performed alongside @tati-qalified. 

### Things to be aware of:
- None

### Things to worry about:
- None

2023-12-01 16:55 UTC, filipelautert approved these changes

2023-12-04 17:03 UTC, merged