Proposed fix for #5442
liquibase/liquibase pull request #5446
Opened 2024-01-08 20:29 UTC by Tylorjg

## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

Issue #5442 outlines an odd behavior where the `unexpected-changesets` command shows the `tag` changeset as unexpected. If using the `tag` command itself, a changeset is not added to the changelog, but an internal Liquibase changeset will be added to the DBCL table. This would cause the `unexpected-changesets `to always show the internal Liquibase changeset as unexpected. Side note, the `generate-changelog` does not create the changeset in a changelog if it exists in the DBCL, so there isn't a way to make the tag expected.

This fix adds a function that is called first to determine if the file path is the **liquibase-internal** changeset. If it is, it removes it from the unexpected list. 

## Things to be aware of

I couldn't find a way to capture the file path for the ran changeset in the RanChangesSet.java file, so I did the same call that occurs in the isSameAs function (occurs in the isSamePath function technically), so it could be refactored to be more efficient. 

## Things to worry about

There isn't any additional tests associated with the change. I have found that there is a file unexpectedChangesets.test.groovy, but was unsure how to get the `tag` command to execute first. I would be happy to write test cases/modify the existing ones.

## Additional Context

N/A

2024-01-18 17:59 UTC, MalloD12 reviewed
Hi @Tylorjg,

Thank you for adding submitting this PR to fix #5442. I was thinking maybe we can only update `isSameAs()` by also checking whether `filepath` is equals to `"liquibase-internal" `. Something like this:

```
public boolean isSameAs(ChangeSet changeSet) {
        return isSamePath("liquibase-internal") || (
                this.getId().equalsIgnoreCase(changeSet.getId())
                && this.getAuthor().equalsIgnoreCase(changeSet.getAuthor())
                && isSamePath(changeSet.getFilePath()));
    }
```
Then we don't need to create a new method nor update `ExpectedChangesVisitor` class.

Regarding tests, I think it would be nice if we can add some integration test [here](https://github.com/liquibase/liquibase/tree/master/liquibase-integration-tests/src/test/groovy/liquibase/command/core) by creating a new class (UnexpectedChangesetsCommandStepTest), for adding this test you can also use `CommandUtil` test class where you have a `runTag()` and probably you can also add a `runUnexpectedChangeset()` to validate the given issue.

Please let me know if you have any question/concerns.

Thanks,
Daniel.

2024-01-29 21:47 UTC, MalloD12 approved these changes
**Approved**.

Thanks @Tylorjg for submitting this PR and addressing my review comment. I have manually tested this change, plus also adding a basic integration test to validate your fix against MySQL in this case, but it could against any DB.

Build and test checks have been successfully executed (there are some functional test failing, but that doesn't seem to be related with this change.

2024-01-30 10:24 UTC, filipelautert approved these changes

2024-01-30 21:54 UTC, rberezen requested changes
@Tylorjg @filipelautert @MalloD12 
The fix introduces a regression. So, if you execute the following commands:

1. liquibase tag tag1
2. liquibase update
3. liquibase history

you will observe that it appears as though nothing was deployed; the databasechangelog will be empty, but the deployed objects will exist in the database.
![image](https://github.com/liquibase/liquibase/assets/30054788/71bd40f3-bbcc-414f-bfd8-b10a802e9ca9)
![image](https://github.com/liquibase/liquibase/assets/30054788/c8753493-a344-43e6-abde-39609faa5143)

2024-01-31 13:17 UTC, MalloD12 commented
@Tylorjg would you mind looking at the regression issue @rberezen mentioned above?

Thanks,
Daniel.

2024-02-19 17:31 UTC, MalloD12 commented
Code changes look good to me, thank you for taking care of this regression issue @Tylorjg.

@rberezen would you mind trying again when you have a chance?

Thanks,
Daniel.

2024-02-20 22:59 UTC, rberezen approved these changes

2024-02-26 11:53 UTC, filipelautert requested changes

2024-02-26 11:53 UTC, filipelautert commented on liquibase-standard/src/main/java/liquibase/changelog/RanChangeSet.java
> +        String normalizedFilePath = DatabaseChangeLog.normalizePath(this.getChangeLog());
Hey @Tylorjg ! I just noticed those changes to RanChangeSet (moving the normalizedFilePath from isSamePath to isSameAs methods. Seems they were part of some other tests but are not necessary here anymore - so could we rollback them ? The idea of calling normalize path at method isSamePath is that if author or id doesn't match them we never reach this expensive normalization.

2024-02-29 17:34 UTC, filipelautert approved these changes

2024-02-29 17:34 UTC, merged