Fix default end delimiter applied when there is an endDelimiter applied for a given chanset
liquibase/liquibase pull request #5781
Opened 2024-04-09 11:13 UTC by MalloD12

## Impact

- [x] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

When `endDelimiter` is specified in a changeset no default endDelimiter should be added to the SQL visitors to be applied. 

Fixes #5603
 

## Things to be aware of
- `AppendSqlIfNotPresentVisitor` will be only applied when there is no endDelimiter set for a changeset. 

## Things to worry about
- Not really, this is only applicable for MSSQL and it will only be applied if there is not endDelimiter specified.

## Additional Context
- None

2024-04-18 16:27 UTC, filipelautert requested changes

2024-04-18 16:27 UTC, filipelautert commented on liquibase-standard/src/main/java/liquibase/database/core/MSSQLDatabase.java
> +            super.executeStatements(change, changeLog, sqlVisitors);
In this case a sqlvisitor for the provided end delimiter is already defined?

2024-04-18 16:54 UTC, filipelautert approved these changes

2024-04-25 22:34 UTC, MalloD12 commented
@filipelautert @wwillard7800: I updated the logic added in this PR to avoid not appending the `;` at the end when it should. Logic now is:

```
if (change instanceof AbstractSQLChange) {
            String endDelimiter = StringUtil.trimToNull(((AbstractSQLChange) change).getEndDelimiter());
            if (endDelimiter != null && !endDelimiter.contentEquals(";")) {
                super.executeStatements(change, changeLog, sqlVisitors);
            } else {
                super.executeStatements(change, changeLog, addSqlVisitors(sqlVisitors));
            }
        }
        else {
                super.executeStatements(change, changeLog, addSqlVisitors(sqlVisitors));
            }
```
What this will do is, if endDelimiter is set, but it's a `;` it should append it at the end as it was happening, but if it's not a `;` it won't append it at the end. I'm not 100% sure of this, for example, if `endDelimiter` set is `/` what should we do in that case, should it be appended anyway? Your feedback will be very appreciated.

@rberezen: I think this should fix the current issue, but anyway this would be pending on whether this is an appropriate fix or not. 

Thanks,
Daniel.

2024-04-29 21:23 UTC, filipelautert approved these changes

2024-04-29 21:56 UTC, rberezen approved these changes
Looks good to me, tests passed. 
cc @filipelautert @MalloD12

2024-05-08 13:32 UTC, merged