GitHub action dat 17643
liquibase/liquibase pull request #5936
Opened 2024-05-21 15:23 UTC by StevenMassaro

## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

## Things to be aware of

## Things to worry about

## Additional Context

2024-05-21 17:10 UTC, filipelautert approved these changes

2024-05-21 17:11 UTC, filipelautert requested changes
Seems liquibase-cli doesn't have any tests?

Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project liquibase-cli: No tests were executed!  (Set -DfailIfNoTests=false to ignore this error.) -> [Help 1]

2024-05-21 17:19 UTC, StevenMassaro commented
> Seems liquibase-cli doesn't have any tests?
> 
> Error: Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project liquibase-cli: No tests were executed! (Set -DfailIfNoTests=false to ignore this error.) -> [Help 1]

That is because the integration test modules only run the integration tests, not the unit tests. Take a look at the build results from this link, which include the changes I made to run-tests.yml: https://github.com/liquibase/liquibase/actions/runs/9177484033/job/25235621246

2024-05-22 19:02 UTC, filipelautert approved these changes

2024-05-29 15:50 UTC, merged