DAT-18067
liquibase/liquibase pull request #6056
Opened 2024-06-28 20:47 UTC by sayaliM0412

Secret with Minimal permission to run the tests. 
Adding authorize step for external PR's

fix: `.github/workflows/run-functional-tests.yml`
fix: `.github/workflows/run-test-harness.yml`

## Impact

- [ ] Bug fix (non-breaking change which fixes expected existing functionality)
- [ ] Enhancement/New feature (adds functionality without impacting existing logic)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
 

## Description

## Things to be aware of

## Things to worry about

## Additional Context

2024-06-28 22:04 UTC, rberezen requested changes
@sayaliM0412 tests are not triggered for non-forked pr

2024-07-01 14:22 UTC, sayaliM0412 commented
> Details

I think you need to create a external forked branch from my branch `DAT-18067` and also add it as a base branch to test this.

2024-07-01 14:23 UTC, sayaliM0412 commented
> @sayaliM0412 tests are not triggered for non-forked pr

I think you need to create a external forked branch from my branch `DAT-18067` and also add it as a base branch to test this. @rberezen

2024-07-01 19:53 UTC, sayaliM0412 commented
> @sayaliM0412 tests are not triggered for non-forked pr

just had to update the branch . It's running fine now : https://github.com/liquibase/liquibase/actions/runs/9749908865?pr=6056

2025-01-16 18:45 UTC, closed without merging