analytics tracking (DAT-17058)
liquibase/liquibase pull request #6412
Opened 2024-10-10 13:59 UTC by liquibot

This PR introduces the ability for Liquibase to gather anonymous usage analytics when commands are run via the CLI. No user-specific data will be gathered. 

For Liquibase OSS users, this functionality will be enabled by default, but can be opted-out of before any data is sent. For Liquibase Pro users, this will disabled by default with the ability to opt-in. 

Only the versions of Liquibase after this PR goes into a future release will have the ability to gather anonymous analytics. Those versions will have this functionality on or off immediately when used for the first time as specified above. There are sections below that instruct how to turn this on or off as desired. 

## Why are we doing this?

Gathering anonymous usage analytics allows us to better understand how Liquibase is actually being used by a very wide, diverse set of millions of users. This data will help our small team help our users better by providing insight into things like:

- What commands are the most used:  if some commands are never used it might mean we need to reconsider that command’s purpose, provide more resources to help increase usage, or even remove the command entirely.
- What commands result in the most failures: knowing this will help us identify gaps in documentation or the product itself.
- What database platforms are the most used with Liquibase: this information will help us identify where we should focus our efforts to maximize benefit for our users.
- What version of Java are our users on: this will help us as we consider updating Java versions in core and many extensions.
- What version of Liquibase are users on: this will help us understand if users are updating regularly or where we might help with updates.

## What information are we gathering?
If the functionality is enabled and a user is not opted-out, Liquibase will record the following information when a command is run via the CLI:

- Command-specific data like: command name, if the command succeeded or failed, and exception data if there is a failure
- Liquibase data including version and interface that it’s being run in
- Database platform including version 
- Changelog information like number of changelogs run and changelog formats
- Extension information like which extensions are being used and what version
- Pro feature information like which features are enabled
- Operating system information like type of OS, version, and architecture

To reiterate, we are not gathering any personally identifiable information. This data is all aggregated and anonymous.

## Where to view the information we gather

We are working to make analytics events and certain parts of the data that we collect publicly available on the web. 

## Opting Out
  
If you do not want to participate in Liquibase anonymous analytics, there are a number of ways to opt-out at any time. 

Per CLI command, you can add the parameter `--analytics-enabled=false`. This will turn off analytics gathering for that single occurrence of a command (ie. `liquibase status –analytics-enabled=false`).

If you would like to turn off the functionality globally, you can add `liquibase.analytics.enabled: false` to your defaults file or use the environment variable LIQUIBASE_ANALYTICS_ENABLED: false.

## Opting In

If you are a Pro user or someone that previously disabled Liquibase anonymous analytics, there are a number of ways to opt-in. 

Per CLI command, you can add the parameter `--analytics-enabled=true`. This will turn on analytics gathering for that single occurrence of a command (ie. `liquibase status --analytics-enabled=true`).

If you would like to turn on the functionality globally, you can add `liquibase.analytics.enabled: true` to your defaults file or use the environment variable LIQUIBASE_ANALYTICS_ENABLED: true.

## More Information

If you have any questions or feedback please respond to this issue or email us - product@liquibase.com. 

Documentation for this new functionality can be found at https://docs.liquibase.com/analytics.

2024-10-11 14:38 UTC, filipelautert requested changes

2024-10-11 14:38 UTC, filipelautert commented on liquibase-standard/src/main/java/liquibase/analytics/AnalyticsBatch.java
> +public class AnalyticsBatch {
Could you add javadoc here?

2024-10-11 14:38 UTC, filipelautert commented on liquibase-standard/src/main/java/liquibase/analytics/LiquibaseAnalyticsListener.java
> +@NoArgsConstructor
Could you add javadoc here?

2024-10-11 14:38 UTC, filipelautert commented on liquibase-standard/src/main/java/liquibase/analytics/configuration/LiquibaseRemoteAnalyticsConfiguration.java
> +public class LiquibaseRemoteAnalyticsConfiguration implements AnalyticsConfiguration {
Could you add javadoc here?

2024-10-11 14:39 UTC, filipelautert commented
@StevenMassaro I marked 3 points in new classes were some javadoc would be helpful.

2024-10-11 20:17 UTC, filipelautert approved these changes

2024-10-23 18:16 UTC, filipelautert approved these changes

2024-10-23 19:58 UTC, merged

2024-11-11 15:23 UTC, sideeffffect commented
In case somebody is interested in turning it off programmatically, here's an easy way
 * https://github.com/sideeffffect/liquibase-doobie/pull/426